name: Model Training and Push

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger on
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Train the model
    - name: Train the model
      run: |
        source venv/bin/activate
        python app/train.py

    # Set Git configuration for GitHub Actions user
    - name: Set Git config
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"

    # Commit and push changes (model file)
    - name: Commit and push model
      run: |
        git add models/logistic_regression_model.pkl
        git commit -m "Automated model training update [GitHub Actions]"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
